name: Print out the content of Zama file

on: [push]

jobs:
  print-content:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Print out Zama file
      run: cat zama-file
